#!/bin/bash
# NEXTFLOW TASK: average_coefficient
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/e2/f96c836c166c9930cbd95048b2eb60/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/e2/f96c836c166c9930cbd95048b2eb60/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f raw_result1
    rm -f raw_result2
    rm -f raw_result3
    rm -f raw_result4
    rm -f raw_result5
    rm -f raw_result6
    rm -f raw_result7
    rm -f raw_result8
    rm -f raw_result9
    rm -f raw_result10
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/68/827f80218922e79f942f859b0790de/raw_result.rds raw_result1
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/25/b5e69ee72c42184efae4f67ed67521/raw_result.rds raw_result2
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/c2/ba6b324181e8f7036dd9a926c055e8/raw_result.rds raw_result3
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/84/4d4799d542c78cd912e70f959528dc/raw_result.rds raw_result4
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/e7/e757c55f59e19db4bc5bf4dbfd444b/raw_result.rds raw_result5
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/6a/76befcb631dd48846aaafb18e7a863/raw_result.rds raw_result6
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/9a/98badc256009b14904f777fecb40a3/raw_result.rds raw_result7
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/85/ec29f8c60b07a58a452fed9a9305d2/raw_result.rds raw_result8
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/c0/c36e4c4d6d19dbe577f87a1d168ccc/raw_result.rds raw_result9
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/18/4108680c0a2119e0e578b9a2306659/raw_result.rds raw_result10
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/e2/f96c836c166c9930cbd95048b2eb60/.command.begin
    set +u
    set -u
    export PATH="/Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/bin:$PATH"
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    local ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
