#!/bin/bash
# NEXTFLOW TASK: average_coefficient
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/db/b29e40123b484d2fdd30792ad1eac9/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/db/b29e40123b484d2fdd30792ad1eac9/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f raw_result1
    rm -f raw_result2
    rm -f raw_result3
    rm -f raw_result4
    rm -f raw_result5
    rm -f raw_result6
    rm -f raw_result7
    rm -f raw_result8
    rm -f raw_result9
    rm -f raw_result10
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/a8/06636245997c1e869daff02e771fc4/raw_result.rds raw_result1
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/28/a5d28328be9492f79ea2d43d6a5d5c/raw_result.rds raw_result2
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/a3/bb4be611527b3c67bcda781c7661ba/raw_result.rds raw_result3
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/a5/e8daefeed9a6a769c79f9ff1bac9a4/raw_result.rds raw_result4
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/93/aab2220117259386040ef606482002/raw_result.rds raw_result5
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/70/fcdcae7b782be0da5b89b6e77f6aa5/raw_result.rds raw_result6
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/3c/28a8b63b752bf4325572ade5a6cdb0/raw_result.rds raw_result7
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/74/a3536ef716cc006dca8595b9d62b7d/raw_result.rds raw_result8
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/2b/3d36bfb816c413ffba15fa7d8b9717/raw_result.rds raw_result9
    ln -s /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/aa/fb1e4f0ebdf4f2e699208d60762bb3/raw_result.rds raw_result10
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/work/db/b29e40123b484d2fdd30792ad1eac9/.command.begin
    set +u
    set -u
    export PATH="/Users/Administrator/Desktop/samson1/CMU/year1_summer/research/nextflow/distributed_linear_regresion/bin:$PATH"
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    local ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
